const constants  = {
    FORKS_THRESHOLD : 100,
    FORKS_WEIGHT : 1,
    STARS_THRESHOLD : 150,
    STARS_WEIGHT: 1,
    CLOSEDISSUE_THRESHOLD: 5000,
    CLOSEDISSUE_WEIGHT : 0.5,
    CONTRIBUTORS_THRESHOLD : 5000,
    CONTRIBUTORS_WEIGHT : 2,
    COMMITFREQUENCY_THRESHOLD : 15,
    COMMITFREQUENCY_WEIGHT : 1,
    CREATED_AT_THRESHOLD : 120,
    CREATED_AT_WEIGHT : 1,
    UPDATED_AT_THRESHOLD : 120,
    UPDATED_AT_WEIGHT : -1,
    RELEASES_THRESHOLD : 26,
    RELEASES_WEIGHT : 0.5,
}

module.exports = constants;
